volumes:
  postgres_volume:

services:
  payment_app:
    build:
      context: ..
      dockerfile: payment_service/Dockerfile
    restart: always
    environment:
      - PORT=8084
      - DATABASE_HOST=payment_db
      - DATABASE_PORT=5432
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=payment_db
    depends_on:
      - payment_db
    ports:
      - "8084:8084"
    networks:
      - cassette-world

  payment_db:
    image: postgres:latest
    container_name: payment_db
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./dev/SQL:/docker-entrypoint-initdb.d/
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - cassette-world

networks:
  cassette-world:
    external:
      name: cassette-world
