listener:
  port: ":8089"

databases:
  postgres:
    host: localhost
    port: 5434
    user: test_user
    password: test_password
    name: test_user_db

  localStorage:
    userAvatarsFullURL: images/user_avatars/
    userAvatarsRelativeURL: images/user_avatars/
