listener:
  port: ":8082"

databases:
  postgres:
    host: user_db
    port: 5432
    user: test
    password: test
    name: user_db

  localStorage:
    userAvatarsFullURL: /home/ubuntu/images/user_avatars/
    userAvatarsRelativeURL: /images/user_avatars/
