// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: review.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReviewClient is the client API for Review service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	GetQuestionData(ctx context.Context, in *GetQuestionDataRequest, opts ...grpc.CallOption) (*GetQuestionDataResponse, error)
	CheckPass(ctx context.Context, in *CheckPassRequest, opts ...grpc.CallOption) (*CheckPassResponse, error)
	CreateFront(ctx context.Context, in *CreateFrontRequest, opts ...grpc.CallOption) (*CreateFrontResponse, error)
}

type reviewClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewClient(cc grpc.ClientConnInterface) ReviewClient {
	return &reviewClient{cc}
}

func (c *reviewClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/review.Review/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) GetQuestionData(ctx context.Context, in *GetQuestionDataRequest, opts ...grpc.CallOption) (*GetQuestionDataResponse, error) {
	out := new(GetQuestionDataResponse)
	err := c.cc.Invoke(ctx, "/review.Review/GetQuestionData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) CheckPass(ctx context.Context, in *CheckPassRequest, opts ...grpc.CallOption) (*CheckPassResponse, error) {
	out := new(CheckPassResponse)
	err := c.cc.Invoke(ctx, "/review.Review/CheckPass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) CreateFront(ctx context.Context, in *CreateFrontRequest, opts ...grpc.CallOption) (*CreateFrontResponse, error) {
	out := new(CreateFrontResponse)
	err := c.cc.Invoke(ctx, "/review.Review/CreateFront", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServer is the server API for Review service.
// All implementations must embed UnimplementedReviewServer
// for forward compatibility
type ReviewServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	GetQuestionData(context.Context, *GetQuestionDataRequest) (*GetQuestionDataResponse, error)
	CheckPass(context.Context, *CheckPassRequest) (*CheckPassResponse, error)
	CreateFront(context.Context, *CreateFrontRequest) (*CreateFrontResponse, error)
	mustEmbedUnimplementedReviewServer()
}

// UnimplementedReviewServer must be embedded to have forward compatible implementations.
type UnimplementedReviewServer struct {
}

func (UnimplementedReviewServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedReviewServer) GetQuestionData(context.Context, *GetQuestionDataRequest) (*GetQuestionDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionData not implemented")
}
func (UnimplementedReviewServer) CheckPass(context.Context, *CheckPassRequest) (*CheckPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPass not implemented")
}
func (UnimplementedReviewServer) CreateFront(context.Context, *CreateFrontRequest) (*CreateFrontResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFront not implemented")
}
func (UnimplementedReviewServer) mustEmbedUnimplementedReviewServer() {}

// UnsafeReviewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewServer will
// result in compilation errors.
type UnsafeReviewServer interface {
	mustEmbedUnimplementedReviewServer()
}

func RegisterReviewServer(s grpc.ServiceRegistrar, srv ReviewServer) {
	s.RegisterService(&Review_ServiceDesc, srv)
}

func _Review_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_GetQuestionData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).GetQuestionData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/GetQuestionData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).GetQuestionData(ctx, req.(*GetQuestionDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_CheckPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).CheckPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/CheckPass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).CheckPass(ctx, req.(*CheckPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_CreateFront_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFrontRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).CreateFront(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/CreateFront",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).CreateFront(ctx, req.(*CreateFrontRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Review_ServiceDesc is the grpc.ServiceDesc for Review service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Review_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "review.Review",
	HandlerType: (*ReviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Review_Create_Handler,
		},
		{
			MethodName: "GetQuestionData",
			Handler:    _Review_GetQuestionData_Handler,
		},
		{
			MethodName: "CheckPass",
			Handler:    _Review_CheckPass_Handler,
		},
		{
			MethodName: "CreateFront",
			Handler:    _Review_CreateFront_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}
