services:
  fascade_app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - /home/ubuntu/images:/home/ubuntu/images
    ports:
      - 8080:8080
    networks:
      - cassette-world

  nginx:
    build: ./nginx
    # volumes:
    #   - ../frontend/2024_2_GOATS/dist:/var/www/dist
    #   - ../disk:/usr/share/nginx/html/static
    #   - ../images:/usr/share/nginx/html/images
    #   - ../frontend/2024_2_GOATS/public/assets:/usr/share/nginx/html/assets
    ports:
      - 80:80
    depends_on:
      - fascade_app
    restart: "always"
    networks:
      - cassette-world

networks:
  cassette-world:
    external: true
