volumes:
  elasticsearch_data:

services:
  facade_app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - cassette-world

  nginx:
    build: ./nginx
    volumes:
      - ../frontend/2024_2_GOATS/dist:/var/www/dist
      - ../disk:/usr/share/nginx/html/static
      - ../images:/usr/share/nginx/html/images
      - ../frontend/2024_2_GOATS/public/assets:/usr/share/nginx/html/assets
    ports:
      - 80:80
    depends_on:
      - facade_app
    restart: "always"
    networks:
      - cassette-world
  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - "xpack.security.enabled=false"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    networks:
      - cassette-world

networks:
  cassette-world:
    external:
      name: cassette-world
