volumes:
  redis:

services:
  auth_app:
    container_name: auth_app
    image: unicoyal/auth_app:latest
    build:
      context: ..
      dockerfile: auth_service/Dockerfile
    restart: always
    ports:
      - 8081:8081
    networks:
      - cassette-world
  redis:
    image: 'redis:latest'
    command: redis-server
    container_name: redis
    volumes:
      - redis:/data
    networks:
      - cassette-world
networks:
  cassette-world:
    external:
      name: cassette-world
