// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	errors "github.com/go-park-mail-ru/2024_2_GOATS/internal/app/errors"
	models "github.com/go-park-mail-ru/2024_2_GOATS/internal/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthRepositoryInterface is a mock of AuthRepositoryInterface interface.
type MockAuthRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryInterfaceMockRecorder
}

// MockAuthRepositoryInterfaceMockRecorder is the mock recorder for MockAuthRepositoryInterface.
type MockAuthRepositoryInterfaceMockRecorder struct {
	mock *MockAuthRepositoryInterface
}

// NewMockAuthRepositoryInterface creates a new mock instance.
func NewMockAuthRepositoryInterface(ctrl *gomock.Controller) *MockAuthRepositoryInterface {
	mock := &MockAuthRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepositoryInterface) EXPECT() *MockAuthRepositoryInterfaceMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *MockAuthRepositoryInterface) DestroySession(ctx context.Context, cookie string) (*errors.ErrorObj, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, cookie)
	ret0, _ := ret[0].(*errors.ErrorObj)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockAuthRepositoryInterfaceMockRecorder) DestroySession(ctx, cookie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).DestroySession), ctx, cookie)
}

// GetFromCookie mocks base method.
func (m *MockAuthRepositoryInterface) GetFromCookie(ctx context.Context, cookie string) (string, *errors.ErrorObj, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromCookie", ctx, cookie)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errors.ErrorObj)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// GetFromCookie indicates an expected call of GetFromCookie.
func (mr *MockAuthRepositoryInterfaceMockRecorder) GetFromCookie(ctx, cookie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromCookie", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).GetFromCookie), ctx, cookie)
}

// SetCookie mocks base method.
func (m *MockAuthRepositoryInterface) SetCookie(ctx context.Context, token *models.Token) (*models.CookieData, *errors.ErrorObj, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCookie", ctx, token)
	ret0, _ := ret[0].(*models.CookieData)
	ret1, _ := ret[1].(*errors.ErrorObj)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// SetCookie indicates an expected call of SetCookie.
func (mr *MockAuthRepositoryInterfaceMockRecorder) SetCookie(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCookie", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).SetCookie), ctx, token)
}
