volumes:
  redis:
  postgres_volume:

services:
  movie_app:
    build:
      context: ..
      dockerfile: movie_service/Dockerfile
    restart: always
    volumes:
      - /home/ubuntu/images:/home/ubuntu/images
    environment:
      - PORT=8082
      - DATABASE_HOST=movie_db
      - DATABASE_PORT=5433
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=movie_db
    depends_on:
      - movie_db
    networks:
      - cassette-world

  movie_redis:
    image: 'redis:latest'
    command: redis-server
    container_name: movie_redis
    volumes:
      - redis:/data
    networks:
      - cassette-world

  movie_db:
    image: postgres:latest
    container_name: movie_db
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./dev/SQL:/docker-entrypoint-initdb.d/
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - cassette-world

networks:
  cassette-world:
    external:
      name: cassette-world
