volumes:
  postgres_volume:

services:
  review_app:
    build:
      context: ..
      dockerfile: review_service/Dockerfile
    restart: always
    # volumes:
    #   - /home/ubuntu/images:/home/ubuntu/images
    ports:
      - 8081:8081
    networks:
      - cassette-world
  review_db:
    image: postgres:latest
    container_name: review_db
    environment:
      - "POSTGRES_DB=review_db"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
    volumes:
      - ./dev/SQL:/docker-entrypoint-initdb.d/
      - "postgres_volume:/var/lib/postgresql/data"
    networks:
      - cassette-world
networks:
  cassette-world:
    external: true
