// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: validation.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Validation_ValidateRegistration_FullMethodName = "/validation.Validation/ValidateRegistration"
)

// ValidationClient is the client API for Validation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidationClient interface {
	ValidateRegistration(ctx context.Context, in *ValidateRegistrationRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
}

type validationClient struct {
	cc grpc.ClientConnInterface
}

func NewValidationClient(cc grpc.ClientConnInterface) ValidationClient {
	return &validationClient{cc}
}

func (c *validationClient) ValidateRegistration(ctx context.Context, in *ValidateRegistrationRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, Validation_ValidateRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidationServer is the server API for Validation service.
// All implementations must embed UnimplementedValidationServer
// for forward compatibility.
type ValidationServer interface {
	ValidateRegistration(context.Context, *ValidateRegistrationRequest) (*ValidationResponse, error)
	mustEmbedUnimplementedValidationServer()
}

// UnimplementedValidationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidationServer struct{}

func (UnimplementedValidationServer) ValidateRegistration(context.Context, *ValidateRegistrationRequest) (*ValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRegistration not implemented")
}
func (UnimplementedValidationServer) mustEmbedUnimplementedValidationServer() {}
func (UnimplementedValidationServer) testEmbeddedByValue()                    {}

// UnsafeValidationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidationServer will
// result in compilation errors.
type UnsafeValidationServer interface {
	mustEmbedUnimplementedValidationServer()
}

func RegisterValidationServer(s grpc.ServiceRegistrar, srv ValidationServer) {
	// If the following call pancis, it indicates UnimplementedValidationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Validation_ServiceDesc, srv)
}

func _Validation_ValidateRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServer).ValidateRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Validation_ValidateRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServer).ValidateRegistration(ctx, req.(*ValidateRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Validation_ServiceDesc is the grpc.ServiceDesc for Validation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Validation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "validation.Validation",
	HandlerType: (*ValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateRegistration",
			Handler:    _Validation_ValidateRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "validation.proto",
}
