// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	os "os"
	reflect "reflect"

	errors "github.com/go-park-mail-ru/2024_2_GOATS/internal/app/errors"
	models "github.com/go-park-mail-ru/2024_2_GOATS/internal/app/models"
	dto "github.com/go-park-mail-ru/2024_2_GOATS/internal/app/user/repository/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateFavorite mocks base method.
func (m *MockUserRepositoryInterface) CreateFavorite(ctx context.Context, favData *dto.RepoFavorite) *errors.RepoError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFavorite", ctx, favData)
	ret0, _ := ret[0].(*errors.RepoError)
	return ret0
}

// CreateFavorite indicates an expected call of CreateFavorite.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateFavorite(ctx, favData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavorite", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateFavorite), ctx, favData)
}

// CreateUser mocks base method.
func (m *MockUserRepositoryInterface) CreateUser(ctx context.Context, registerData *dto.RepoRegisterData) (*models.User, *errors.RepoError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, registerData)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*errors.RepoError)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateUser(ctx, registerData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateUser), ctx, registerData)
}

// DestroyFavorite mocks base method.
func (m *MockUserRepositoryInterface) DestroyFavorite(ctx context.Context, favData *dto.RepoFavorite) *errors.RepoError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyFavorite", ctx, favData)
	ret0, _ := ret[0].(*errors.RepoError)
	return ret0
}

// DestroyFavorite indicates an expected call of DestroyFavorite.
func (mr *MockUserRepositoryInterfaceMockRecorder) DestroyFavorite(ctx, favData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyFavorite", reflect.TypeOf((*MockUserRepositoryInterface)(nil).DestroyFavorite), ctx, favData)
}

// GetFavorites mocks base method.
func (m *MockUserRepositoryInterface) GetFavorites(ctx context.Context, usrID int) ([]models.MovieShortInfo, *errors.RepoError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavorites", ctx, usrID)
	ret0, _ := ret[0].([]models.MovieShortInfo)
	ret1, _ := ret[1].(*errors.RepoError)
	return ret0, ret1
}

// GetFavorites indicates an expected call of GetFavorites.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetFavorites(ctx, usrID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavorites", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetFavorites), ctx, usrID)
}

// SaveUserAvatar mocks base method.
func (m *MockUserRepositoryInterface) SaveUserAvatar(ctx context.Context, avatarName string) (string, *os.File, *errors.RepoError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserAvatar", ctx, avatarName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*os.File)
	ret2, _ := ret[2].(*errors.RepoError)
	return ret0, ret1, ret2
}

// SaveUserAvatar indicates an expected call of SaveUserAvatar.
func (mr *MockUserRepositoryInterfaceMockRecorder) SaveUserAvatar(ctx, avatarName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserAvatar", reflect.TypeOf((*MockUserRepositoryInterface)(nil).SaveUserAvatar), ctx, avatarName)
}

// UpdatePassword mocks base method.
func (m *MockUserRepositoryInterface) UpdatePassword(ctx context.Context, usrID int, pass string) *errors.RepoError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, usrID, pass)
	ret0, _ := ret[0].(*errors.RepoError)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdatePassword(ctx, usrID, pass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdatePassword), ctx, usrID, pass)
}

// UpdateProfileData mocks base method.
func (m *MockUserRepositoryInterface) UpdateProfileData(ctx context.Context, usrData *dto.RepoUser) *errors.RepoError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileData", ctx, usrData)
	ret0, _ := ret[0].(*errors.RepoError)
	return ret0
}

// UpdateProfileData indicates an expected call of UpdateProfileData.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateProfileData(ctx, usrData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileData", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateProfileData), ctx, usrData)
}

// UserByEmail mocks base method.
func (m *MockUserRepositoryInterface) UserByEmail(ctx context.Context, email string) (*models.User, *errors.RepoError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*errors.RepoError)
	return ret0, ret1
}

// UserByEmail indicates an expected call of UserByEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) UserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UserByEmail), ctx, email)
}

// UserByID mocks base method.
func (m *MockUserRepositoryInterface) UserByID(ctx context.Context, userID int) (*models.User, *errors.RepoError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*errors.RepoError)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) UserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UserByID), ctx, userID)
}
