listener:
  port: :8088

databases:
  postgres:
    host: localhost
    port: 5435
    user: test
    password: test
    name: movie_db
    maxOpenConns: 100
    maxIdleConns: 30
    connMaxLifetime: 30
    connMaxIdleTime: 5
