// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2024_2_GOATS/payment_service/internal/payment/repository/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockPaymentRepoInterface is a mock of PaymentRepoInterface interface.
type MockPaymentRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepoInterfaceMockRecorder
}

// MockPaymentRepoInterfaceMockRecorder is the mock recorder for MockPaymentRepoInterface.
type MockPaymentRepoInterfaceMockRecorder struct {
	mock *MockPaymentRepoInterface
}

// NewMockPaymentRepoInterface creates a new mock instance.
func NewMockPaymentRepoInterface(ctrl *gomock.Controller) *MockPaymentRepoInterface {
	mock := &MockPaymentRepoInterface{ctrl: ctrl}
	mock.recorder = &MockPaymentRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepoInterface) EXPECT() *MockPaymentRepoInterfaceMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentRepoInterface) CreatePayment(ctx context.Context, paymentData *dto.RepoPaymentData) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, paymentData)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentRepoInterfaceMockRecorder) CreatePayment(ctx, paymentData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentRepoInterface)(nil).CreatePayment), ctx, paymentData)
}

// MarkPaid mocks base method.
func (m *MockPaymentRepoInterface) MarkPaid(ctx context.Context, pID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaid", ctx, pID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPaid indicates an expected call of MarkPaid.
func (mr *MockPaymentRepoInterfaceMockRecorder) MarkPaid(ctx, pID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaid", reflect.TypeOf((*MockPaymentRepoInterface)(nil).MarkPaid), ctx, pID)
}
