listener:
  address: localhost
  port: 8085
  timeout: 4s
  idleTimeout: 60s
  certFile: test_certificates/certificate.crt
  keyFile: test_certificates/private.key

databases:
  postgres:
    host: localhost
    port: 5433
    user: test_user
    password: test_password
    name: test_db

  redis:
    host: localhost
    port: 6379
    cookie:
      maxAge: 84400s
      name: session_id

  localStorage:
    userAvatarsFullUrl: images/user_avatars/
    userAvatarsRelativeUrl: images/user_avatars/
