listener:
  port: ":8084"

databases:
  postgres:
    host: payment_db
    port: 5432
    user: payment_user
    password: payment_user_password
    name: payment_db
    maxOpenConns: 100
    maxIdleConns: 30
    connMaxLifetime: 30
    connMaxIdleTime: 5
