listener:
  port: ":8087"

databases:
  postgres:
    host: localhost
    port: 5434
    user: test_user
    password: test_password
    name: test_payment_db
    maxOpenConns: 100
    maxIdleConns: 30
    connMaxLifetime: 30
    connMaxIdleTime: 5

  localStorage:
    userAvatarsFullURL: images/user_avatars/
    userAvatarsRelativeURL: images/user_avatars/
